### PR TITLE
Table: column visibility dropdown list too long

### PR DESCRIPTION
**Pull request by rjavier-trimbler**
## Description
-adding some css properties to set a propper height for column visibility 
-new maxHeight  prop for ModusTableToolbar to be able to change this outside.

References #2155 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by J-Ruiz1** [comment]
Validated that the column visibility behaves as expected, evidence can be found here https://e-builderinc.atlassian.net/browse/NAV-519

**Comment by cjwinsor** [comment]
@Roliver-Javier I was going to approve this, but see now that a max height property was added for the menu which I disagree with being needed at this time. Can you remove this change?  I see no reason to add a property for this unless there is a strong demand for this level of flexibility.  

But now that I am thinking about it, we probably want some sensible min height though so it doesn't collapse into nothingness.

**Comment by rjavier-trimbler** [comment]
> @Roliver-Javier I was going to approve this, but see now that a max height property was added for the menu which I disagree with being needed at this time. Can you remove this change? I see no reason to add a property for this unless there is a strong demand for this level of flexibility.
> 
> But now that I am thinking about it, we probably want some sensible min height though so it doesn't collapse into nothingness.

Hi @cjwinsor yeah, the purpose of this one is because we have some views that are using the table with different spaces and when the toolbar collapses it looks too long (the number of columns will determine the height) so in this case we can set the maximum and the content will be scrollable.

**Comment by dnarey** [comment]
Hey @cjwinsor.  Thanks for the feedback.  The addition of a max height property was from our UX team.  I asked if they could please add a summary and justification, which they included here: https://e-builderinc.atlassian.net/browse/NAV-519?focusedCommentId=381716

Please let us know if there is anything else you need, or if we should take a different approach.  Thank you!

**Comment by cjwinsor** [comment]
@Roliver-Javier After some discussion with Teja and @yohernandez and @dnarey, for now lets use the tables `maxHeight` as the `maxHeight` of the menu.  If the table doesn't have a `maxHeight` defined, then use 60dvh (not vh) as the height so it can account for mobile keyboard sorta elements.  This will allow us to postpone adding a new property to the api until we get more feedback to support it as a necessity. This means that the height will be set on the element, vs a css clas.  Let me know if you have any questions.

**Comment by J-Ruiz1** [comment]
Validated that maxHeight is set to 60dvh

image

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
