### PR TITLE
Fix Accessibility Errors on the User Input Components

### PR DESCRIPTION
**Pull request by msankaran0712**
The `aria-` attributes moved from the `div` to the `input` element. 

Note: 
Did not fix the `aria-placeholder` on the Number Input Component as it is not clear whether it is okay to remove the attribute.

References #1044

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — COMMENTED** [review]
I've spotted some issues:

- `aria-readonly` isn't being set correctly. On this URL: https://deploy-preview-1611--modus-webcomponents.netlify.app/?path=/story/user-inputs-text-input--default&args=ariaLabel:;readOnly:true;required:true the element receives `aria-readonly` with no value which means it is NOT readonly. For the element to be ready-only it needs to be `aria-readonly="true"` (as the default is false). Overall, I think it maybe better to not use ARIA label - you can simply set the readonly HTML attribute and that will be announced to   assistive tools.

- I don't see an issue with the `aria-disabled` implementation, but f the disabled attribute is being added too then the aria-disabled label isn't needed.

- `aria-required` is not set correctly. It should be `aria-required="true"`

- `aria-placeholder` is not set correctly. Suggest to use standard placeholder HTML attribute instead.

- This might be a Storybook bug, but if I change the input type to password I see a serious a11y warning 'aria-label attribute cannot be used on a div with no valid role attribute.' It looks like `aria-label` is on the div but with no label added - can it be removed altogether as to not cause potential issues?

**Comment by msankaran0712** [comment]
> * `required`

@coliff I have removed redundant `aria-disabled`, `aria-placeholder` and `aria-readonly` as we have the corresponding attribute to represent the state and for password text input, added a button role to the div.

**Comment by coliff** [comment]
Not working right now - the generated HTML code for the input is:

```html
<input aria-disabled="true" aria-label="Text Input" aria-readonly="" aria-required="" aria-placeholder="" class="text-align-left" disabled="" inputmode="" maxlength="100" minlength="0" placeholder="" readonly="" tabindex="0" type="password" autofocus="">
```

Here's the a11y panel in DevTools
image

**Review by ryan-henness-trimble — APPROVED** [review]

**Comment by msankaran0712** [comment]
> Not working right now - the generated HTML code for the input when I turn on disabled/readonly and required is:
> 
> ```
> <input 
> aria-disabled="true" 
> aria-label="Text Input" 
> aria-readonly="" 
> aria-required="" 
> aria-placeholder="" 
> class="text-align-left" 
> disabled="" 
> inputmode="" 
> maxlength="100" 
> minlength="0" 
> placeholder="" 
> readonly="" 
> tabindex="0" 
> type="password" 
> autofocus="">
> ```
> 
> Here's the a11y panel in DevTools image

@coliff Thats weird because Azure deploy does not have the latest fix. Please check the Netlify preview once https://deploy-preview-1611--modus-webcomponents.netlify.app/?path=/story/user-inputs-text-input--default&args=disabled:true;readOnly:true;required:true;type:password

**Review by coliff — APPROVED** [review]

**Pull request merged**
