### PR TITLE
Added Modus Time Picker component

### LINKED ISSUE #973: Time Picker in Web Components

### PR DESCRIPTION
**Pull request by msankaran0712**
Fixes #973 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?
Chrome Browser

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
should this have `maxlength="5"`?

**Comment by msankaran0712** [comment]
> Many systems/countries use 24-hour clock, I don't think we should enforce entering PM or AM.
> 
> I don't really see why using this would ever be preferable over using input `type="time"` which supports 12/24 hour clock, step inputs, localization/internationalization, validation and min and max time. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

Good question, maybe I went ahead with the assumption that we are not using the native time picker. I will confirm it with @egunther39.

**Comment by ryan-henness-trimble** [comment]
This feels like something a developer could build using the Text Input and Selection components 🤔 I wonder if we should add this formatting/logic as options for the Text Input for the Time portion, and expect devs to use the Selection component for the timezones

**Comment by msankaran0712** [comment]
> This feels like something a developer could build using the Text Input and Selection components 🤔 I wonder if we should add this formatting/logic as options for the Text Input for the Time portion, and expect devs to use the Selection component for the timezones - just my first thought

That's a good idea. We can combine Text input, Number input and Time input. I need a couple more days to do that so I think we can create a separate issue. what do you think @ryan-henness-trimble ?

**Comment by msankaran0712** [comment]
hey, @coliff removed maxLength as it seemed redundant, since we have a specific time format and autoformat options, there is no specific use case to support it, also the native input="time" doesn't have it too. We have manually added maxLength inside the code.

**Review by ryan-henness-trimble — APPROVED** [review]

**Comment by ryan-henness-trimble** [comment]
> > This feels like something a developer could build using the Text Input and Selection components 🤔 I wonder if we should add this formatting/logic as options for the Text Input for the Time portion, and expect devs to use the Selection component for the timezones - just my first thought
> 
> That's a good idea. We can combine Text input, Number input and Time input. I need a couple more days to do that so I think we can create a separate issue. what do you think @ryan-henness-trimble ?

Oh hmm - I forgot about the Number input to be honest. I wonder if it would be better to just keep them separate

**Review by coliff — APPROVED** [review]

**Pull request merged**
