### PR TITLE
Tabs: make individual tabs buttons

### PR DESCRIPTION
**Pull request by austinoneil**
## Description

Make individual tabs buttons, give containing div `"tablist"` role

References #2143 (tabs section)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

https://deploy-preview-2360--moduswebcomponents.netlify.app/?path=/docs/components-tabs--default

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
Nice! Code looks ok to me, but the CSS needs updating.
https://deploy-preview-2360--moduswebcomponents.netlify.app/?path=/docs/components-tabs--default
looks different to production site:
https://modus-web-components.trimble.com/?path=/docs/components-tabs--default

**Comment by austinoneil** [comment]
Fixed.  It looks like it was an issue with the background.

**Comment by coliff** [comment]
I think just need to fix the font-family now... it's displaying as 'Arial' with your PR - should be `"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`

**Comment by austinoneil** [comment]
@coliff fixed

**Comment by coliff** [comment]
Oh, there's an accessibility violation with this:

image

**Comment by austinoneil** [comment]
> Oh, there's an accessibility violation with this:
> 
> image

fixed

**Comment by coliff** [comment]
The accessibility error is still present. Not sure about that image you uploaded as its not loading now. I think best way to resolve this could to remove `role="tablist"`.

**Comment by coliff** [comment]
@austinoneil - I'll approve and merge this if you could kindly remove `role="tablist"` altogether.

**Comment by austinoneil** [comment]
> @austinoneil - I'll approve and merge this if you could kindly remove `role="tablist"` altogether.

Done and changed the name of the PR to reflect this change.

**Review by coliff — APPROVED** [review]

**Pull request merged**
