### PR TITLE
Select: Add placeholder prop

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Added an initial option to the existing options list which is selected by default is disabled ,value is empty and is hidden. 
- The text content of the added option is "Please help which is the place holder value by default and can be modified with the placeholder prop.

References #
#1476 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
@coliff Can you help validate if there are any accessibility issues with this implementation?

**Comment by coliff** [comment]
Let's make the demo iframe a bit taller so the Custom Placeholder one is visible without needing to scroll down in the iframe.
image

For the placeholder, instead of making it the option `hidden`, can we instead just make it `disabled`. See this demo: https://stackblitz.com/edit/modus-select?file=index.html
That way a user must select a different option when opened.

**Comment by cjwinsor** [comment]
Can you also add 24px padding between the the examples

**Comment by ElishaSamPeterPrabhu** [comment]
> Can you also add 24px padding between the the examples

Have added br that seems enough, should it be 24px?

**Comment by ElishaSamPeterPrabhu** [comment]
> * Let's make the demo iframe a bit taller so the Custom Placeholder one is visible without needing to scroll down in the iframe.
>   image
> * This should have linebreaks to prevent it requiring horizontal scroll - supect Prettier formatting it will fix it:
>   image
> * For the placeholder, instead of making it the option `hidden`, can we instead just make it `disabled`. See this demo: https://stackblitz.com/edit/modus-select?file=index.html
>   That way a user must select a different option when opened.

- Added line breaks, increased height in storybook.
- Removed hidden property for placeholder option

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
