### PR TITLE
Add Theme toggler for storybook

### LINKED ISSUE #787: Dark Mode for Web components - Theme Toggle Component
Once we've got our pattern for setting the theme on the Page Level, a `ThemeToggle` component should be created that will switch the theme globally. This will allow consumers of the library to get 'out of the box' theme toggling

### PR DESCRIPTION
**Pull request by msankaran0712**
Added a theme toggler using a [addon](https://storybook.js.org/addons/storybook-dark-mode) that uses local storage to retain the theme selection and also checks for user preference.
Also added some styles in the storybook for dark mode.

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #787 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
PR deploy preview works well and Storybook itself looks great in dark mode, but none of the components are dark-mode ready yet.

Adding a dark mode toggle before the work is done may give the impression to users that dark mode is supported.

Not sure what the best thing to do right now is, but maybe it's possible to always load Storybook in light-mode until a later date and maybe have the toggle as semi-hidden? (e.g., change CSS opacity of the button to 0.1)? Or alternatively add a message somewhere which shows in dark mode saying that it isn't currently officially supported like we do on Modus next gen site:

image

**Comment by msankaran0712** [comment]
> PR deploy preview works well and Storybook itself looks great in dark mode, but none of the components are dark-mode ready yet.
> 
> Adding a dark mode toggle before the work is done may give the impression to users that dark mode is supported.
> 
> Not sure what the best thing to do right now is, but maybe it's possible to always load Storybook in light-mode until a later date and maybe have the toggle as semi-hidden? (e.g., change CSS opacity of the button to 0.1)? Or alternatively add a message somewhere which shows in dark mode saying that it isn't currently officially supported like we do on Modus next gen site:
> 
> image

We can hide the toggler for now, and show it when we finish the components.

**Comment by coliff** [comment]
> We can hide the toggler for now, and show it when we finish the components.

If you have an idea on how to have it available but hidden that'd be really helpful for us as we work on it as we'll be able to test future PRS which add dark-mode support to components as we go along. The CSS to have the button invisible would be simple enough... not tested but I think this would work.

```css
button[title="Change theme to light mode"] {
  opacity: 0 !important;
}
```

**Comment by coliff** [comment]
If I open `https://icy-ground-0374a1310-792.centralus.1.azurestaticapps.net/` in a new incognito window it still loads in dark mode.

**Comment by msankaran0712** [comment]
> If I open `https://icy-ground-0374a1310-792.centralus.1.azurestaticapps.net/` in a new incognito window it still loads in dark mode.

Switch to light mode once to hide the toggler and it renders a `light` theme in my chrome incognito window :|

**Comment by coliff** [comment]
my system and browser preference is dark-mode and the site loads in incognito mode in dark mode in both Edge v106 and Chrome v106....

**Review by ryan-henness-trimble — DISMISSED** [review]

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
cool. will need to remember to update the CHANGELOG with whatever the status is of darkmode before the next release. Maybe it can be released from CHANGELOG if it's not ready.

**Pull request merged**
