### PR TITLE
Checkbox : Linked checkbox and label for Screen Reader Accessibility

### LINKED ISSUE #2078: Checkbox: Accessibility Issues
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Checkboxes are currently not accessible at all via screen readers. The label should be linked to the checkbox input but they are not.

image

### Reduced test cases

I used NVDA on Windows 11 and tabbed across this test page:
https://coliff.github.io/modus-web-components-example/#checkbox

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v.0.13.0

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

https://modus-web-components.trimble.com/

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

- Created Unique Id for Label and Checkbox 
- Linked the Label and checkbox with Id 

References 
Fixes #2078   

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

https://deploy-preview-2486--moduswebcomponents.netlify.app/?path=/story/user-inputs-checkbox--medium

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
There's a regression with this change. Clicking on the label should check or uncheck the checkbox
https://deploy-preview-2486--moduswebcomponents.netlify.app/?path=/story/user-inputs-checkbox--medium

**Comment by prashanthr6383** [comment]
> There's a regression with this change. Clicking on the label should check or uncheck the checkbox https://deploy-preview-2486--moduswebcomponents.netlify.app/?path=/story/user-inputs-checkbox--medium

Hi @coliff , Stop propagation prop is causing this issue; removing this will solve the issue. Please let me know if we can continue using this approach.

**Comment by cjwinsor** [comment]
@prashanthr6383 I am curious if we stop using the svgs and stopped hiding the native input and instead we style the input like modus bootstrap does (https://modus.trimble.com/components/web/checkboxes/, and https://modus-bootstrap.trimble.com/components/checkboxes/), if we can just put the click event on the checkbox itself and simplify. Only downside is we would need to define the svg for the checkmark and line in the scss instead of using an existing icon.  

Can you take a moment to see if using the native checkbox can solve the issue, and if so, can we get it styled as we need? Internally would probably need to be the `change` event instead of `click` though.

I'm not sure why the checkmark is different in those two links though..... Should match this
https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=1346-10&mode=design&t=h9AaVBzyFEf80izP-0

image

**Comment by prashanthr6383** [comment]
> @prashanthr6383 I am curious if we stop using the svgs and stopped hiding the native input and instead we style the input like modus bootstrap does (https://modus.trimble.com/components/web/checkboxes/, and https://modus-bootstrap.trimble.com/components/checkboxes/), if we can just put the click event on the checkbox itself and simplify. Only downside is we would need to define the svg for the checkmark and line in the scss instead of using an existing icon.
> 
> Can you take a moment to see if using the native checkbox can solve the issue, and if so, can we get it styled as we need? Internally would probably need to be the `change` event instead of `click` though.
> 
> I'm not sure why the checkmark is different in those two links though..... Should match this https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=1346-10&mode=design&t=h9AaVBzyFEf80izP-0
> 
> image

@cjwinsor  As discussed, I have replaced those icons and styled the checkbox using CSS. I also updated the click event to change the event. The label event bubbling seems to be fixed now. kindly check

**Comment by prashanthr6383** [comment]
Hi @cjwinsor As discussed , the tab index prop is removed. kindly check and approve

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
@prashanthr6383 - great PR - thanks! 👍

**Pull request merged**
