### PR TITLE
Update StoryBook with adding borderless property to dropdown

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description
Update story book for modifying dropdown UI

References #
#1454 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?
UI changes are dev tested and compared with figma

Previewed in Storybook

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
- Is 'borderless' an option? It's not listed in Properties table. Should it be?
- The dropdown needs a 1px border like this: 
image

**Review by msankaran0712 — APPROVED** [review]
@ElishaSamPeterPrabhu We need the outer border as @coliff mentioned

**Review by msankaran0712 — CHANGES_REQUESTED** [review]
Request changes

**Comment by msankaran0712** [comment]
> * Is 'borderless' an option? It's not listed in Properties table. Should it be?
> * The dropdown needs a 1px border like this:
>   image

@coliff I assume borderless is mandatory for a dropdown list, Please correct me if am wrong.

**Review by rthanga1 — APPROVED** [review]

**Comment by msankaran0712** [comment]
@ElishaSamPeterPrabhu  Closing the PR as the code is duplicate of https://github.com/trimble-oss/modus-web-components/pull/1867

**Pull request closed without merging**
