### PR TITLE
Content Tree: Updated Tree View Item 

### LINKED ISSUE #1596: Modus Content tree - No enough space between the tree view indicator line and drag and drop icon
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Content tree - No enough space between the tree view indicator line and drag and drop icon

Please refer the below screenshot:
image

### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

_No response_

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

### Are you using Modus Web Components in production ?

_No response_

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

- modified state of width to be important

References 
Fixes #1596  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
After discuss with team:
* Make sure space isn't allocated for drag handler unless its show.  Currently it always includes the the drag element but doesn't show the icon until its needed. That space is pushing the expand arrow away too much from the left side
* Make sure to always reserve the space for the selection blue bar indicator, which is currently .3rem in width
image
image
image
image
image

**Comment by prashanthr6383** [comment]
> After discuss with team:
> 
> * Make sure space isn't allocated for drag handler unless its show.  Currently it always includes the the drag element but doesn't show the icon until its needed. That space is pushing the expand arrow away too much from the left side
> * Make sure to always reserve the space for the selection blue bar indicator, which is currently .3rem in width
>   image
>   image
>   image
>   image
>   image

Hi @cjwinsor requested changes are done. kindly check and approve

**Comment by cjwinsor** [comment]
@prashanthr6383 Can you undo my request to remove the drag indicator when not in use? Since each item has its own draggableItem prop, it can cause bad alignment if one item is draggable and the next isn't.  We'll need to revisit how we handle dragging in a later ticket.

**Comment by prashanthr6383** [comment]
> @prashanthr6383 Can you undo my request to remove the drag indicator when not in use? Since each item has its own draggableItem prop, it can cause bad alignment if one item is draggable and the next isn't. We'll need to revisit how we handle dragging in a later ticket.

Hi @cjwinsor reverted back the drag icon to be hidden.

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
