### PR TITLE
Issue 1869 fix modus table reorder

### PR DESCRIPTION
**Pull request by rjavier-trimbler**
## Description
Changes:
ModusTableHeader 
 removed the componentId from the props because is not enough only replace the id from the table header, 
 also there're other places that need to match the header id like `table-header-drag-drop.utility` and the table metadata (headerGroup)  that tanStack uses to update it states. For this is better to update this value from another scope, replacing this new ID from the state and from the table options

componentWillLoad
If we're generating the table ID from this method we can update the columnOrder state with the proper ID and then Initialize the table with the columns matching this ID as well.

 

References #1869 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by apaddock** [comment]
@Roliver-Javier The column visibility feature is now broken. The required columns are now able to be hidden. 

image

**Comment by coliff** [comment]
I've marked this PR as draft. When the issue that @apaddock reported is fixed you can mark it as 'Ready for review' again. Thanks!

**Comment by msankaran0712** [comment]
@rjavier-trimbler @apaddock I have already fixed the issue on a PR: https://github.com/trimble-oss/modus-web-components/pull/1862. It will be ready for release in a day or two, and you can use it.

**Comment by msankaran0712** [comment]
@rjavier-trimbler Sorry for any confusion. I fixed this issue before your PR. Please test it here https://github.com/trimble-oss/modus-web-components/pull/1881 and close this if not needed anymore.

**Review by msankaran0712 — CHANGES_REQUESTED** [review]
Please do not merge the PR before confirming, but it can be closed if not needed anymore

**Comment by msankaran0712** [comment]
@rjavier-trimbler Closing the PR since the fix is published now

**Comment by rjavier-trimbler** [comment]
> Please do not merge the PR before confirming, but it can be closed if not needed anymore

Hi @msankaran0712  I checkout your branch and I still see the issue, the column is not placed where I want to, it always moving the column to the last place

**Comment by msankaran0712** [comment]
@rjavier-trimbler the code is merged to the main branch now, please check again, if there is any unit test work in progress, kindly create a different PR.

**Pull request closed without merging**
