### PR TITLE
Alert: Add button 

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Added a modus-button inside a container which has the dismissible button and modus button.

References #
#1118 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
button is not visible in dark mode:
https://deploy-preview-2142--moduswebcomponents.netlify.app/?path=/story/components-alert--default&args=buttonText:Hello

**Comment by ElishaSamPeterPrabhu** [comment]
> button is not visible in dark mode: https://deploy-preview-2142--moduswebcomponents.netlify.app/?path=/story/components-alert--default&args=buttonText:Hello

Yes, is that an issue in canvas? running locally its visible 
image
A similar issue while emitting actionclick for the action button its not getting read at the canvas but locally when testing it is.
@coliff

**Comment by coliff** [comment]
> Yes, is that an issue in canvas? running locally its visible

That image you posted looks wrong- that can't be dark mode as I see a white background. I'll mark this as draft until you get it fixed and then you can mark as ready for review once sorted.

**Comment by ElishaSamPeterPrabhu** [comment]
> > Yes, is that an issue in canvas? running locally its visible
> 
> That image you posted looks wrong- that can't be dark mode as I see a white background. I'll mark this as draft until you get it fixed and then you can mark as ready for review once sorted.

The button is present but not visible unless hovered or clicked in dark mode but in the type info alone it occurs
image
for example in info-gray-dark the button is visible
image
Its because we are using a borderless button
image
whose font color matches with the alert of type info's dark theme background

**Review by egunther39 — APPROVED** [review]

**Comment by cjwinsor** [comment]
@ElishaSamPeterPrabhu Make the button an outline - secondary button

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Make the button an outline - secondary button

Updated existing borderless button to outline - secondary  button.

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
