### PR TITLE
Barebones Modus Data Table

### PR DESCRIPTION
**Pull request by ryan-henness-trimble**
## Description

Table reference: https://modus.trimble.com/components/tables/

This PR includes the implementation of the barebones Data Table Stencil component, tests, and additional Storybook docs/bug fixes. 

The Data Table is currently a basic implementation that takes columns, data, size, and sort options. 
<details style="color: blue;">
  <summary>🔵 Click for Details, Inputs, Sorting</summary>

### Implementation Details
- The table `columns` property accepts an array of strings, or an array of objects.
  - Defining the columns with objects allows you to define extra properties on the column/column cells.
- The table `data` property accepts either a 2D array of primitive types (`string`, `number`, or `boolean`) or an array of objects.
  - Note: the objects in `data` get their property names mapped to each column `id`.
- The table needs a unique `id` for each column that maps to each cell in that column. If it is not provided, the table will generate a unique id for each column.

### Inputs
Refer to the **Default** example above to see how to define simple `columns` and `data` in the table.

To define columns and data in the table *using objects*:
```html
<modus-data-table />
<script>
    document.querySelector('modus-data-table').columns = [
        { display: 'Name', id: 'name', width: '50%' },
        { display: 'Age', id: 'age', align: 'right' },
        { display: 'Contacted', id: 'contacted' }
    ];

    const john = { name: 'John', age: 25, contacted: false };
    const jane = { name: 'Jane', age: 26, contacted: false };
    const joe = { name: 'Joe', age: 27, contacted: true };
    document.querySelector('modus-data-table').data = [john, jane, joe];
</script>
```

### Sorting
- The table uses a tri-state for its sorting:
  - `none`: no sorting is applied
  - `asc`: ascending sort
  - `desc`: descending sort
- The table sorting options can be set with the optional `sortOptions` property. The property accepts a `ModusTableSortOptions` object.
  - The object defines whether the table can be sorted on header click, and if the sort is done on the client or server-side.
- If the table is sortable, it will output the `sort` event on header click. This event's detail is a `ModusDataTableSortEvent` object.
- If the table's `serverSide` sort option is `false`, it will sort the columns on the client-side. Otherwise, it is up to the consumer to update the table's `data` property with the sorted data.

</details>

Inline stories were broken for Storybook stories that needed properties set through a script tag, I set those stories' `inlineStories` to false.

References #166 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update

## How Has This Been Tested?

Manually, unit, and e2e.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by ryan-henness-trimble** [comment]
@coliff I had a question about the 'readonly' cells. If the table is completely read only, should we still display the cells in a read only style? It seems like it might be better to display them as 'normal' cells with a white background if its completely read only

**Comment by msankaran0712** [comment]
> @coliff @msankaran0712 I had a question about the 'read-only' cells. If the table is completely read-only, should we still display the cells in a read-only style? It seems like it might be better to display them as 'normal' cells with a white background if its completely read-only. It's looking odd to me with only 'read-only' cells in the table so I wanted to double check
> 
> Read-only styling image
> 
> Normal styling image

A read-only table is just a normal table, the cells should not be disabled. You can refer the List table styles in https://modus.trimble.com/components/tables/?q=tabl#types

**Comment by msankaran0712** [comment]
Also are we doing storybook changes in a separate PR ?

**Comment by ryan-henness-trimble** [comment]
> Do we have a preview for these changes?



> > @coliff @msankaran0712 I had a question about the 'read-only' cells. If the table is completely read-only, should we still display the cells in a read-only style? It seems like it might be better to display them as 'normal' cells with a white background if its completely read-only. It's looking odd to me with only 'read-only' cells in the table so I wanted to double check
> > Read-only styling image
> > Normal styling image
> 
> A read-only table is just a normal table, the cells should not be disabled. You can refer the List table styles in https://modus.trimble.com/components/tables/?q=tabl#types

There's two different styles for read-only and normal in the docs

**Comment by ryan-henness-trimble** [comment]
Opening branch PR for static web app deployment

**Comment by msankaran0712** [comment]
@ryan-henness-trimble I think this PR should be moved to `Draft` if you have more commits.

**Comment by ryan-henness-trimble** [comment]
> @ryan-henness-trimble I think this PR should be moved to `Draft` if you have more commits.

it's ready 😄 I just had some small changes

**Review by quynh-le-trimble — APPROVED** [review]
Nice job on all the tests.

**Pull request merged**
