### PR TITLE
Table: Shift select rows multi selection

### LINKED ISSUE #2883: Tables: Click+Shift select rows
https://trimble-arch.aha.io/ideas/ideas/MOD-I-114

Allow Shift+Click and Shift + Up/Down arrow to select multiple rows in a table. The checkboxes are checked to indicate which rows have been selected.

Similar to the behavior in the Content Tree component:
The prop multi-selection lets multiple items to be selected using Shift + Up/Down arrow and Ctrl + click.

Image

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Added Multi selection of rows via shift + arrow keys up and down when row selection is enabled
Note: Multiple selection via click is already handled

References 
Fixes #2883 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by jewel-shajan — CHANGES_REQUESTED** [review]
@ElishaSamPeterPrabhu Unchecking the checkbox does not deselect the row .
image

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Unchecking the checkbox does not deselect the row . image

Fixed the issue, Can you have a look?

**Review by jewel-shajan — APPROVED** [review]

**Review by jewel-shajan — CHANGES_REQUESTED** [review]
When multiple is false  shift+down/up arrow selects multiple items and in large data set  when multiple is true its not working.

**Comment by ElishaSamPeterPrabhu** [comment]
> When multiple is false

@jewel-shajan 
Still doesn't work with large dataset, Please carry out the other tests

**Comment by jewel-shajan** [comment]
> > When multiple is false
> 
> @jewel-shajan Still doesn't work with large dataset, Please carry out the other tests

@ElishaSamPeterPrabhu Even when "multiple" is set to false, using Ctrl or Shift + Up/Down arrow still selects multiple items. Additionally, when unchecking the checkbox, the row selection remains.

**Comment by ElishaSamPeterPrabhu** [comment]
> > > When multiple is false
> > 
> > 
> > @jewel-shajan Still doesn't work with large dataset, Please carry out the other tests
> 
> @ElishaSamPeterPrabhu Even when "multiple" is set to false, using Ctrl or Shift + Up/Down arrow still selects multiple items. Additionally, when unchecking the checkbox, the row selection remains.

@jewel-shajan addressed the issues

**Comment by ElishaSamPeterPrabhu** [comment]
@jewel-shajan Updated the selections based on this discussion https://github.com/trimble-oss/modus-web-components/issues/2883#issuecomment-2514793896

**Review by jewel-shajan — CHANGES_REQUESTED** [review]
@ElishaSamPeterPrabhu When pagination is enabled, if we select rows from multiple pages, the selection changes randomly when switching between pages.

**Comment by ElishaSamPeterPrabhu** [comment]
> When pagination is enabled, if we select rows from multiple pages, the selection changes randomly when switching between pages.

@jewel-shajan ,Addressed these issues.

**Comment by jewel-shajan** [comment]
@ElishaSamPeterPrabhu When the expandable row option is enabled and the row selection option is set to multiple: false, the event emission does not behave as expected.

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu When the expandable row option is enabled and the row selection option is set to multiple: false, the event emission does not behave as expected.



> @ElishaSamPeterPrabhu When the expandable row option is enabled and the row selection option is set to multiple: false, the event emission does not behave as expected.

Addressed the issue

**Review by jewel-shajan — APPROVED** [review]

**Review by jewel-shajan — COMMENTED** [review]
Testing completed and ready for PR Review.

**Pull request merged**
