### PR TITLE
Modal: Accessibility updates

### PR DESCRIPTION
**Pull request by austinoneil**
## Description

* When not visible, role is not "dialog"
* When visible, has "aria-modal" attribute
* When not visible, "aria-label" is not present
* When not visible, "aria-hidden" is true

References #2076 (note: I am leaving the final bullet point off, as that is a breaking change and I am not an employee/owner and there seems to be ambiguity as to whether or not we should implement that change.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

E2E tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
this is great - thanks!
https://deploy-preview-2374--moduswebcomponents.netlify.app/?path=/docs/components-modal--default

Can see the DOM of the modal when closed is:
`<div class="modus-modal overlay hidden" style="z-index: 1;" aria-hidden="true">`
when open it is:
`<div class="modus-modal overlay visible" style="z-index: 1;" aria-label="Modal" aria-modal="true" role="dialog">`

Exactly what we needed 👍

**Review by coliff — CHANGES_REQUESTED** [review]
Oops, found an accessibility bug in the Canvas demo - aria-label is in the DOM even if no value is provided:
image

**Comment by austinoneil** [comment]
I am seeing the same issue in [prod's storybook.](https://modus-web-components.trimble.com/?path=/story/components-modal--default&args=ariaLabel:). As is, it looks like a blank string is being treated like a presence of an `aria-label`.  I'm not sure whether this would be considered a bug/issue.

**Comment by coliff** [comment]
> I am seeing the same issue in [prod's storybook.](https://modus-web-components.trimble.com/?path=/story/components-modal--default&args=ariaLabel:). As is, it looks like a blank string is being treated like a presence of an `aria-label`. I'm not sure whether this would be considered a bug/issue.

It is a problem. The Modal causes a violation in the Accessibility panel. We want to get all them resolved. There should never be any `aria-label=""` anywhere in any of the code in any of the components. Really, this is an issue we should resolve in all the Modus Web Components...

Overall, the changes in this PR are an improvement so I'm thinking we should merge as it is and look at improving further in a different issue/PR. For now, perhaps we just remove the 'Modal' value from `aria-label` in the Storybook Canvas. That way there will no accessibility issues reported at all in Storybook for the Modal component.
Demo: https://deploy-preview-2374--moduswebcomponents.netlify.app/?path=/story/components-modal--default&args=ariaLabel:

**Comment by austinoneil** [comment]
@coliff I have filed  #2409

**Comment by coliff** [comment]
> For now, perhaps we just remove the 'Modal' value from `aria-label` in the Storybook Canvas. That way there will no accessibility issues reported at all in Storybook for the Modal component.

I pushed this change and will merge. thanks! 👍

**Review by coliff — APPROVED** [review]

**Pull request merged**
