### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ryan-henness-trimble**
Add a basic CONTRIBUTING file.

References #378

### CODE REVIEW

**Comment by gallelauren816** [comment]
This is so helpful, Ryan. Thanks so much for creating this. It is easy to follow and all makes sense to me!

**Review by gallelauren816 — COMMENTED** [review]
Looks great! Thanks so much. Are there any specifics you wanted to include about what content is required when updating the change log file? I remember there being specific categories of changes that can be added to this (i.e. fixed, added, etc.). Not super necessary but potentially helpful for devs like me who don't add to this code very often. Other than that, this is awesome!!

**Comment by ryan-henness-trimble** [comment]
> Looks great! Thanks so much. Are there any specifics you wanted to include about what content is required when updating the change log file? I remember there being specific categories of changes that can be added to this (i.e. fixed, added, etc.). Not super necessary but potentially helpful for devs like me who don't add to this code very often. Other than that, this is awesome!!

Good idea. There are some details in the README, but it would probably be nice for me to point that out so devs know to check there

**Review by gallelauren816 — DISMISSED** [review]

**Review by trimbleo — APPROVED** [review]
Looks good to me.

**Question:**
Is developing the components with storybook the way you would recommend developing against a component?

**Comment by ryan-henness-trimble** [comment]
> Looks good to me.
> 
> **Question:** Is developing the components with storybook the way you would recommend developing against a component?

I usually just develop them against the index file that acts as the dev environment index for Stencil. I haven't set up a way to live rerender the Storybook site on component changes. Should I call that out?

**Comment by trimbleo** [comment]
> I usually just develop them against the index file that acts as the dev environment index for Stencil. I haven't set up a way to live rerender the Storybook site on component changes. Should I call that out?

Yes please. It should be called out, but not a blocker for this PR.
Do you just import the component you are working on into the index.html

**Pull request merged**
