### PR TITLE
Pagination: Icon Issue fix

### PR DESCRIPTION
**Pull request by HarieshPugazhendhi**
## Description

- Adjusted the thickness of the left and right icons in the pagination component to achieve a uniform appearance.
- Updated relevant CSS styles to ensure proper rendering of the adjusted icons.

References #
#568

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

-  Verified that the left and right icons in pagination have been updated to use the desired thickness.
- Manually tested the pagination component in the browsers to ensure consistent display and functionality.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — DISMISSED** [review]
This is a big improvement - thanks! 👍

**Review by cjwinsor — CHANGES_REQUESTED** [review]
This change makes the `icon-chevron-left-thick` and `icon-chevron-right-thick` have the svg for the non thick version.  I feel we need to move away from the old svgs folder.  Can we either:

1. Rename the files to remove the `thick` and rename the export to not include `Thick` as that is now misleading

OR

2. Update Pagination control to use `ModusIconMap` instead and use the generated icons instead

```jsx
import { ModusIconMap } from '../../icons/ModusIconMap';

<ModusIconMap icon="chevron_left" size={this.chevronSizeBySize.get(this.size)} />
<ModusIconMap icon="chevron_right" size={this.chevronSizeBySize.get(this.size)} />
``` 

Alternatively you could reference them directly from generated folder
```jsx
import { IconChevronLeft } from '../../icons/generated-icons/IconChevronLeft';
import { IconChevronRight } from '../../icons/generated-icons/IconChevronRight';

<IconChevronLeft size={this.chevronSizeBySize.get(this.size)} />
<IconChevronRight size={this.chevronSizeBySize.get(this.size)} />
```

**Comment by cjwinsor** [comment]
@HarieshPugazhendhi Just checking if you meant to push latest changes after that last comment or it was just a confirmation of approach.

**Comment by cjwinsor** [comment]
@HarieshPugazhendhi Also looks like an older PR that just got merged caused a conflict with your changes.  Can you pull in the latest main to resolve?

**Review by coliff — CHANGES_REQUESTED** [review]
heya- changes in the PR looks good but there are merge conflicts. Please get them resolved so we can approve and merge :-)

**Comment by coliff** [comment]
This branch has conflicts that must be resolved still. I'll mark this as Draft until that's resolved so we know when to re-review.

**Comment by HarieshPugazhendhi** [comment]
> > This change makes the `icon-chevron-left-thick` and `icon-chevron-right-thick` have the svg for the non thick version. I feel we need to move away from the old svgs folder. Can we either:
> > 
> > 1. Rename the files to remove the `thick` and rename the export to not include `Thick` as that is now misleading
> > 
> > OR
> > 
> > 2. Update Pagination control to use `ModusIconMap` instead and use the generated icons instead
> > 
> > ```js
> > import { ModusIconMap } from '../../icons/ModusIconMap';
> > 
> > <ModusIconMap icon="chevron_left" size={this.chevronSizeBySize.get(this.size)} />
> > <ModusIconMap icon="chevron_right" size={this.chevronSizeBySize.get(this.size)} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Alternatively you could reference them directly from generated folder
> > ```js
> > import { IconChevronLeft } from '../../icons/generated-icons/IconChevronLeft';
> > import { IconChevronRight } from '../../icons/generated-icons/IconChevronRight';
> > 
> > <IconChevronLeft size={this.chevronSizeBySize.get(this.size)} />
> > <IconChevronRight size={this.chevronSizeBySize.get(this.size)} />
> > ```
> 
> * Renamed the files by removing the thick at the end.
> * Renamed the export file that include thick.




> This change makes the `icon-chevron-left-thick` and `icon-chevron-right-thick` have the svg for the non thick version. I feel we need to move away from the old svgs folder. Can we either:
> 
> 1. Rename the files to remove the `thick` and rename the export to not include `Thick` as that is now misleading
> 
> OR
> 
> 2. Update Pagination control to use `ModusIconMap` instead and use the generated icons instead
> 
> ```js
> import { ModusIconMap } from '../../icons/ModusIconMap';
> 
> <ModusIconMap icon="chevron_left" size={this.chevronSizeBySize.get(this.size)} />
> <ModusIconMap icon="chevron_right" size={this.chevronSizeBySize.get(this.size)} />
> ```
> 
> Alternatively you could reference them directly from generated folder
> 
> ```js
> import { IconChevronLeft } from '../../icons/generated-icons/IconChevronLeft';
> import { IconChevronRight } from '../../icons/generated-icons/IconChevronRight';
> 
> <IconChevronLeft size={this.chevronSizeBySize.get(this.size)} />
> <IconChevronRight size={this.chevronSizeBySize.get(this.size)} />
> ```

Since I have forked this repository, I am unable rename the files to remove the thick.

**Comment by cjwinsor** [comment]
Closing as we are fixing in #2221

**Pull request closed without merging**
