### PR TITLE
Add transition animation to accordions

### LINKED ISSUE #690: Modus Accordions should have transition animations
See Modus Bootstrap's accordions:
https://modus-bootstrap.trimble.com/components/accordions/#examples

It should be relatively straight-forward to add by just adding some CSS

### PR DESCRIPTION
**Pull request by msankaran0712**
Using the `display:` style prop on an element makes transition ineffective. We built a workaround inspired by [Bootstrap 5](https://getbootstrap.com/docs/5.2/dist/js/bootstrap.js) which basically uses timeout to set the collapse state on an accordion item.

Preview: https://deploy-preview-916--modus-webcomponents.netlify.app/?path=/docs/components-accordion--default

Fixes #690 

Note: 
I disabled a couple of unit test cases for accordions as mentioned in a comment below, hope @ryan-henness-trimble can help fix this. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

Chrome

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by msankaran0712** [comment]
hey, @ryan-henness-trimble I need your help fixing a couple of existing test cases for accordions. I have introduced timeouts in the accordion to animate transition and in the test cases custom events 'opened', and 'closed' is not happening as expected after the timeout is completed. I used jest's [mock timer](https://jestjs.io/docs/timer-mocks) logic, but no luck.

**Comment by coliff** [comment]
Great work on the animations. Super smooth! 👍

**Comment by ryan-henness-trimble** [comment]
@msankaran0712 It seems like it would be ok to add a timeout here to wait a bit. It could probably be smaller than `2000`: 
```js
    await element.click();
    await new Promise((r) => setTimeout(r, 2000)); // Wait some time for the timeout event to emit
    await page.waitForChanges();
    expect(opened).toHaveReceivedEvent();
```

**Comment by msankaran0712** [comment]
> @msankaran0712 It seems like it would be ok to add a timeout here to wait a bit. It could probably be smaller than `2000`:
> 
> ```js
>     await element.click();
>     await new Promise((r) => setTimeout(r, 2000)); // Wait some time for the timeout event to emit
>     await page.waitForChanges();
>     expect(opened).toHaveReceivedEvent();
> ```

It works!! Thanks @ryan-henness-trimble

**Comment by msankaran0712** [comment]
hey @ryan-henness-trimble shall we close this one ?

**Review by enowak1031 — APPROVED** [review]
Nice animation!

**Pull request merged**
