### PR TITLE
Storybook: Upgrade to version 8.4

### LINKED ISSUE #1143: Update to Storybook v8.x
Storybook v8 is a major new version with lots of new features and big improvements. It has been in development for more than a year and was recently finally published live.

https://storybook.js.org/docs/react/migration-guide

It'd be great to update our site to use this! We need to test this properly before deploying.

cc @cjwinsor

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Migrated version to 8 with the help of [Storybook v8 Migration Guide](https://storybook.js.org/docs/react/migration-guide)

References 
Fixes #1143 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

Tested in Chrome (Version-130.0.6723.117)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
Running list of Storybook issues I've spotted:

- Dark mode styles aren't right, e.g. text is dark grey on dark grey (important)
- Loading button isn't displaying right https://deploy-preview-2983--moduswebcomponents.netlify.app/?path=/docs/components-button--docs&globals=backgrounds.grid:!true#loading-button
- Expanded Accordions are too tall (too much vertical padding?) https://deploy-preview-2983--moduswebcomponents.netlify.app/?path=/docs/components-accordion--docs&globals=backgrounds.grid:!false#condensed
- flash from dark mode to light mode (very minor)

**Comment by ElishaSamPeterPrabhu** [comment]
> Running list of Storybook issues I've spotted:
> 
> * Dark mode styles aren't right, e.g. text is dark grey on dark grey (important)
> * Loading button isn't displaying right https://deploy-preview-2983--moduswebcomponents.netlify.app/?path=/docs/components-button--docs&globals=backgrounds.grid:!true#loading-button
> * Expanded Accordions are too tall (too much vertical padding?) https://deploy-preview-2983--moduswebcomponents.netlify.app/?path=/docs/components-accordion--docs&globals=backgrounds.grid:!false#condensed
> * flash from dark mode to light mode (very minor)

- Loading button is issue is fixed

- Accordion has this weird behavior when running locally it has the same height when expanded like the other examples 

  image
  the code difference i seem to find is in the deploy preview a `<p>` tag is added to the text "content"
  I also don't find this `<p>` tag being added in the current storybook as well

- Fixed the table css so so the content is clear irrespective of theme

  I found some css is being inherited from somewhere by default, maybe the dark mode styles hence are not applied properly.

- I didn't see any flash so far while switching themes

**Comment by coliff** [comment]
I made a few more tweaks and improvements. The strange spacing on the `<p>` was caused by the `p` tag having `line-height:24px`. I set this to `unset` and it's fixed the issue now I think.

**Comment by coliff** [comment]
@jewel-shajan - this is ready for you to review now! once approved we'll get it merged. thanks!

**Review by jewel-shajan — COMMENTED** [review]
Testing has beeen completed and all the observations are noted down in the below document: [StoryBook 8.4 Observations](https://docs.google.com/document/d/1mza5Gvu0Q8LSugK9bDRdI9tNpSTR3SMmHhQTZugXz3U/edit?usp=drive_link)

**Review by coliff — APPROVED** [review]

**Pull request merged**
