### PR TITLE
Table - Show original page after adding or removing row

### PR DESCRIPTION
**Pull request by janwiebe-glasbergen**
## Description
Draft because:
- Would like to get some feedback on the change from functional component to component?
Are the auto updated readme good enough?
- No new e2e tests added yet:
I was unable to add e2e tests, because pagination is not working correctly in puppeteer (also on main). The pagination components are shown, but the data is not filtered. Any suggetions on how to fix this?

References #1996

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?
Tested by the storybook components (modus-table/manual-pagination and modus-table/pagination)

- Open table at last page
- Remove last item
- Change in pagination should be reflected in the data. 
(In the storybook manual-pagination component, the manual pagination is configured to go to page 1).

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
> Would like to get some feedback on the change from functional component to component?
I'll need more time to evaluate the changes to have an answer. Any information on why this change was made specifically would be useful (Needed state? Access to lifecycle methods for X reason?, etc).  I haven't worked with this area of modus yet, but I'll take a deeper look tomorrow.

>Are the auto updated readme good enough?
yes

> I was unable to add e2e tests, because pagination is not working correctly in puppeteer (also on main). The pagination components are shown, but the data is not filtered. Any suggetions on how to fix this?
If you can provide the test case or a code snippet that reproduces the issue I can help take a look.

**Comment by janwiebe-glasbergen** [comment]
@cjwinsor 

The reason for moving from functional component to a component was to have the a life-cycle hook for componentWillRender to prevent some warnings.

For the e2e tests:

If you add the follow snippet to modus-table.e2e.ts:
```typescript
fit('Display current page when content is changed', async () => {
    page = await newE2EPage();
    await page.setContent('<modus-table pageSizeList="" />');

    const component = await page.find('modus-table');

    component.setProperty('pageSizeList', [1, 2, 5]);
    // additional waitForChanges added for testing
    await page.waitForChanges();
    component.setProperty('columns', MockColumns);
    component.setProperty('data', [...MockData, { mockColumnOne: 'Mock Data One 3', mockColumnTwo: 900293 }]);
    await page.waitForChanges();
    component.setProperty('pagination', true);
    await page.waitForChanges();
    await new Promise(r => setTimeout(r, 25000));
  })
  ```
  

You will get a pagination menu, but it doesn't work like expected (see added gif).
- Item 1-3 is shown in the pagination menu, even though page size of 1 is selected
- When switching the page size, the pagination menu shows the correct result, but this is not reflected in the table.

pagination

**Comment by cjwinsor** [comment]
@janwiebe-glasbergen I noticed the when a row is added, it loads the first row for a moment then finally loads the selected page again.  I'm going to spend a little time looking into this to understand what might be causing this and if its something introduced by this change.  

Each frame is slowed down considerably in this recording.
add-row-delay

**Comment by cjwinsor** [comment]
@janwiebe-glasbergen After careful analysis, I found that there is a `autoResetPageIndex` property we can set to false when constructing the Tanstack Table which solves this issue.  Tomorrow I am going to vet out this change and if successful, I will close this PR and create my owns with that fix applied.  If there are issues with this setting, I will discuss them here.

**Comment by cjwinsor** [comment]
This PR was closed as it will be handled with #2129

**Comment by cjwinsor** [comment]
@janwiebe-glasbergen Unfortunately this wasn't able to be merged today.  Although `autoResetPageIndex` is the property we need to set, after enabling it, the table no longer tracks the page index properly.  This hopefully will just need a day or two to sort out and get the full fix in.  Further updates will be in #2129

**Pull request closed without merging**
