### PR TITLE
Modus Table: Update z-index

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

References #1876 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
There are z-index issues with this:
https://deploy-preview-2033--moduswebcomponents.netlify.app/?path=/story/components-table--large-dataset
image

**Comment by cjwinsor** [comment]
@ElishaSamPeterPrabhu 
I will say the issue that was originally reported was fixed at some point leading up to this PR, perhaps with the use of the popper library.  
image

I did notice that with this PR, there still remains one area at least where the tooltip is under another element.
image

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu I will say the issue that was originally reported was fixed at some point leading up to this PR, perhaps with the use of the popper library. image
> 
> I did notice that with this PR, there still remains one area at least where the tooltip is under another element. image

@cjwinsor 
This issue exists in the main branch 
image
The first image is from the main branch?
It is fixed in this PR
The second issue exists in the main branch as well , and its connected to another issue of having an empty column in the table

**Review by cjwinsor — APPROVED** [review]

**Comment by cjwinsor** [comment]
@coliff Anything you want to check on this before it's merged?

**Pull request merged**
