### PR TITLE
Content Tree: Event trigger on shift arrow keys

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

Created a function to handle click event using <kbd>shift</kbd> + <kbd>arrow  keys</kbd> 

Fixes #1713

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
@prashanthr6383 Can you take a look to make sure that the `itemClick` event is fired for the correct element when its selected and deselected via the shift arrow keys?  If I add a listener to a single element (Social) and i select the item above it first, then do shift down, it doesn't fire the event, but when i unselect it, it does with shift up.  It also fires on shift down, which shoudl trigger the item click for the below item, not Social.  Double check the arg that is returned as well: True for selected, False for unselected

**Comment by prashanthr6383** [comment]
> @prashanthr6383 Can you take a look to make sure that the `itemClick` event is fired for the correct element when its selected and deselected via the shift arrow keys? If I add a listener to a single element (Social) and i select the item above it first, then do shift down, it doesn't fire the event, but when i unselect it, it does with shift up. It also fires on shift down, which shoudl trigger the item click for the below item, not Social. Double check the arg that is returned as well: True for selected, False for unselected

@cjwinsor Updated the code. Now the event trigger for shift up and shift down will return true for selected and false for unselected, but though the `itemClick` seems to be firing correctly, the selected element is the previous one. Can you confirm once if this is the expected behavior of shift + arrow or still needs to be fixed?

**Review by prashanth-offcl — CHANGES_REQUESTED** [review]
I see a lot of duplicate events emitted while selecting an option, please check.

**Comment by prashanthr6383** [comment]
> I see a lot of duplicate events emitted while selecting an option, please check.

I am not able to reproduce it. may be a storybook issue kindly re-check

**Comment by prashanth-offcl** [comment]
@prashanthr6383 Currently in multiselect mode If I want to implement a behavior based on selection change then I have to listen to both itemClick (tree-view-item) and itemChange (tree-view). Ideally one event at the parent level should be enough and it should be emitted whenever there is a change wrt selection, be it keyboard or mouse click. 

After introducing itemChange the itemClick event is not really necessary but lets keep it for backward compatibility and have this documented in the storybook.

**Review by prashanth-offcl — APPROVED** [review]

**Pull request merged**
