### PR TITLE
Button: add critical action feature

### LINKED ISSUE #1439: Critical Action Button in Web Components

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

References 

Fixes #1439 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

https://deploy-preview-2871--moduswebcomponents.netlify.app/?path=/story/components-button--danger-button&args=criticalAction:true

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by enowak1031** [comment]
Can we make "Accessibility Warning" text bold and remove the comma before "as." Otherwise, it's good to go :)

**Comment by prashanthr6383** [comment]
> @prashanthr6383 By default, the critical-action in Storybook is set to true, but it should be changed to false.

I have updated now please check

**Comment by prashanthr6383** [comment]
> Can we make "Accessibility Warning" text bold and remove the comma before "as." Otherwise, it's good to go :)

@enowak1031 changes Updated.

**Review by coliff — CHANGES_REQUESTED** [review]
ECE84131-7A86-4151-A27B-A5AF1B0A94BF_4_5005_c

This doesn't work on iPad (Tested on iPad Pro with iPadOS 18.2)

**Comment by prashanthr6383** [comment]
> ECE84131-7A86-4151-A27B-A5AF1B0A94BF_4_5005_c Doesn't work on iPad

@coliff Yes. it Doesn't work on touch screen devices for now. So we have updated the storybook documentation as per discussion on meeting.

**Comment by prashanthr6383** [comment]
> ECE84131-7A86-4151-A27B-A5AF1B0A94BF_4_5005_c
> 
> This doesn't work on iPad (Tested on iPad Pro with iPadOS 18.2)

@coliff Added the support for touch screen devices.

**Review by jewel-shajan — COMMENTED** [review]
Testing completed and ready for PR Review

**Pull request merged**
