### PR TITLE
Table: Update to disable automatic resetting of page index

### PR DESCRIPTION
**Pull request by cjwinsor**
## Description

I set `autoResetPageIndex` to `false` when constructing the Tanstack Table.  This prevents the page index from automatically being reset when the data is changed.

https://tanstack.com/table/latest/docs/api/features/pagination#autoresetpageindex

References #1996

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

I used the following in `index.html` to validate the addition and removal of data maintained the correct page index.
```html
    <button id="addUser">Add User</button>
    <button id="removeUser">Remove User</button>
    <modus-table pagination column-resize column-reorder></modus-table>
    <script>
      let counter = 0;
      const table = document.querySelector('modus-table');
      table.columns = [{id:'first-name', accessorKey: 'firstName', header: 'First Name'}, {id:'last-name', accessorKey: 'lastName', header: 'Last Name'}];
      table.data = [{firstName:`User ${counter++}`},{firstName:`User ${counter++}`},{firstName:`User ${counter++}`},{firstName:`User ${counter++}`}];
      table.pageSizeList = [3,7,11];
      document.querySelector('#addUser').addEventListener('click', () => {
        table.data = [...table.data, {firstName: `User ${counter++}`}];
      });
      document.querySelector('#removeUser').addEventListener('click', () => {
        table.data = table.data.splice(1, table.data.length);
      });
    </script>
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
Working on correcting test failures

**Comment by cjwinsor** [comment]
Latest update on this is that I got this working in a sample React App (https://stackblitz.com/edit/vitejs-vite-m8p17i?file=src%2FApp.tsxv) so I just need to make sure all the principles apply to our component and don't interfere with manual pagination.

**Comment by janwiebe-glasbergen** [comment]
@cjwinsor Any update on this? Anything I could do to help here?

**Review by jmwood330t — APPROVED** [review]
A change like this, I'm interested in how it affects existing tests. And if there aren't any, what the test plan is. :-)

Thanks,
Jim

**Comment by cjwinsor** [comment]
@janwiebe-glasbergen I'm strongly aiming to get this resolved for next weeks release on the 14th.  I'll let you know if I am going to miss that target and update this PR as soon as I can with the latest code changes.  Since my last update I translated the React example into an isolated stencil component.  I will need to reconcile the changes with our manual pagination offering and I have at least one extra render call I'd like to shake out.  

@jmwood330t The missing test cases will be added before this ticket is reviewed.  The existing test cases were able to detect broken scenarios after my initial change which has been the cause of delay in finishing this out.  Basically, I'll be creating tests to cover what is manually covered in my current `How Has This Been Tested?`.

**Comment by cjwinsor** [comment]
Pending adding my new tests to the branch.  I was just having a little difficulty with clicking on the last page in the pagination component, so I'll pick up with a fresh mind tomorrow.

**Review by coliff — APPROVED** [review]

**Pull request merged**
