### PR TITLE
Modus NavBar - Add tooltip to search button

### LINKED ISSUE #1253: Modus NavBar - Tooltip for Search Icon
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

Adding a tooltip to the Search Icon in NavBar.  

image

It is e-Builder's intent to work on this request.

Ultimately we plan on adding tooltips to all the icons.

### Motivation and context

Giving a label to the icons allows giving additional context to them and remove ambiguity.

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

### PR DESCRIPTION
**Pull request by Sanket8793**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1253 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by msankaran0712** [comment]
The code looks fine, @coliff is trying to help us get the PR preview

**Comment by msankaran0712** [comment]
image
Looking good

**Comment by msankaran0712** [comment]
Preview: https://deploy-preview-1261--modus-webcomponents.netlify.app/?path=/docs/components-navbar--default

**Comment by egunther39** [comment]
@msankaran0712 - Please remove the ellipses, otherwise its fine

**Review by ryan-henness-trimble — APPROVED** [review]

**Comment by cjwinsor** [comment]
> @msankaran0712 - Please remove the ellipses, otherwise its fine

Currently the value is provided by the `searchLabel` prop.  We thought this was better for internationalization and more flexible as we establish the pattern for the other icons.

**Review by coliff — APPROVED** [review]

**Pull request merged**
