### PR TITLE
Table: Fix linting warning resulting from using `any` type

### PR DESCRIPTION
**Pull request by austinoneil**
## Description

Updated type emitted from an event to be more strongly typed, avoiding the lint error from using the `any` type.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by austinoneil** [comment]
An alternate approach would be to use the `unknown` type for the type parameter on `overflowRowAction`.

**Review by coliff — APPROVED** [review]
Thanks! LGTM - confirmed lint error is gone with this PR.

**Comment by cjwinsor** [comment]
@austinoneil I'll check on the use of `unknown` as a replacement for `any` tomorrow.  We switched it to any a week or 2 ago as a quick fix to get our angular builds working without having the time to take a deeper look.  I'll need to see if I can dig back up the open issue with [stenciljs output targets](https://github.com/ionic-team/stencil-ds-output-targets/issues) where this was being discussed later.

**Comment by cjwinsor** [comment]
@austinoneil For this one, when running `npm run build` from any of the angular projects, such as `angular-workspace\ng16`, I get this error, which is what we were getting before we switched this to `any`.

```
> angular-workspace@0.0.0-1 build
> ng run @trimble-oss/modus-angular-components:build:production

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@trimble-oss/modus-angular-components'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts:1371:15 - error TS2305: Module '"@trimble-oss/modus-web-components"' has no exported member 'OverflowAction'.

1371 import type { OverflowAction as IModusTableRowActionsOverflowAction } from '@trimble-oss/modus-web-components';
```

I am good with the update just being to set it to `unknown` for now.  This is the same error we were getting when it was previously using the `TableRowActionsMenuEvent` interface (which is what should be used if a solution is found to support setting it properly while also getting the angular output targets to build.

**Comment by austinoneil** [comment]
@cjwinsor done

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
