### PR TITLE
Content Tree: Add isDraggable property

### LINKED ISSUE #2510: Content Tree: Set draggable on tree, not item
If draggable is set on the content tree, then all items are draggable. Don't deprecate the existing item level property at this time.  There still may be value and we can still honor an item being draggable false.

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Added a property `isDraggable` to set draggable state to all children
References 
Fixes #2510 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by prashanth-offcl** [comment]
@ElishaSamPeterPrabhu Reordering is not working for me in the deploy preview probably due to the need for droppable attribute at the container level as you mentioned. Please check.

**Review by prashanth-offcl — CHANGES_REQUESTED** [review]
@ElishaSamPeterPrabhu Reordering is not working for me in the deploy preview probably due to the need for droppable attribute at the container level as you mentioned. Please check.

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Reordering is not working for me in the deploy preview probably due to the need for droppable attribute at the container level as you mentioned. Please check.

The droppableState is set

**Comment by prashanth-offcl** [comment]
> > @ElishaSamPeterPrabhu Reordering is not working for me in the deploy preview probably due to the need for droppable attribute at the container level as you mentioned. Please check.
> 
> The droppableState is set

@ElishaSamPeterPrabhu  `There still may be value and we can still honor an item being draggable false.` - Can you check if this condition is met?

**Comment by prashanth-offcl** [comment]
@ElishaSamPeterPrabhu Couple of observations

- Mutated props should be declared 'mutable'
- Can we update the draggable prop in initTreeViewItem instead of render
- Can we change the prop name to enableReordering

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Couple of observations
> 
> * Mutated props should be declared 'mutable'
> * Can we update the draggable prop in initTreeViewItem instead of render, generally we should avoid mutating state or prop inside the render to avoid infinite re-renders.
> * Change the prop name to enableReordering

All comments addressed

**Review by prashanth-offcl — APPROVED** [review]

**Pull request merged**
