### PR TITLE
List: Add support for sub-text in list item

### PR DESCRIPTION
**Pull request by Sanket8793**
Added support for sub-text in the modus list item component

## Description

Added support for sub-text in the modus list item component

References #1957 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

We have to provide a value for the sub-text property and that value should be rendered below the slot in the modus list item.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
@Sanket8793 Were there any approved figmas that be referenced to ensure we are meeting design guidelines?  My initial test below may need additional considerations for if its selected, not to mention the lack of space around the text as it conforms to the existing heights (though regular and condensed break those height guidelines)
image

**Comment by Sanket8793** [comment]
@cjwinsor
Approved Design by figma
https://www.figma.com/file/EPVOZA4f4OSCAVs6iBiymw/2023---Navigation-components--contribution-to-modus?type=design&node-id=55-1447&mode=design&t=hoBDcFFobIbNTG1V-0

**Comment by cjwinsor** [comment]
@Sanket8793 In order for this to be approved we'll need a discussion with UX.  Upon review of the style [guidelines](https://modus.trimble.com/components/web/lists/styles/), I see the font size for regular should be 14px, condensed as 12px and large as 16px.  Currently it looks like the original implementation of the list in this repo has regular and large both as 16px with condensed being 12px.

This is significant as by correcting the regular font size to 14px to match the style guidelines, then it takes care of one of the row height issues with adding subtext.  

Next comes the selected icon.  This is not covered in the figma, and the alignment does not seem to be considered in this implementation.  In order to approve the PR, we'll need feedback on the selected icon, and have the addition of the selected icon along with subtext affect the height of the item.

I'd expect something along the lines of 
localhost_3334_ (2)
instead of the current
localhost_3334_ (1)

Have a discussion with your UX and let me know the outcome.  Key points to discuss:
1. Regular Font Size: Confirm reduction to 14px is correct
2. Alignment of selected checkbox (this will be important later as well for any left icon that might be implemented in the future)

**Comment by rthanga1** [comment]
Thank you for your contribution @Sanket8793. I agree with everything said by @cjwinsor. We need set the design guidelines first. The current implementation seems to be too congested. We need proper padding between the title and the subtitle.

**Comment by coliff** [comment]
hey all - I can confirm that regular/default List should have 14px font size (not 16px). Please adjust that in this PR. thanks!

**Comment by jcabrera87** [comment]
This is Dafnee Zambrano, our UX, response: 

> For item 1, these are the modus specs for their dropdown menus. The default size is 12/ large size is 14 and the two-line dropdown has 14 px and 12 px font sizes
image
This is coming out of Modus Figma library, if there are further questions with the styling, please let me know so we can set up a meeting with the Modus UX team and clarify
For item 2, this is a mock-up of a dropdown with two lines. The icon is centered regardless of its size https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=19052%3A48287&mode=design&t=mXpBGIVQZTspt7iX-1

**Comment by Sanket8793** [comment]
@cjwinsor 
I updated the PR with the code changes by adjusting the selected checkbox and found that the font-size for the Regular/Default list item is set to 14px so no changes are needed for that.

image

**Comment by rthanga1** [comment]
@cjwinsor to fill up these details

1. Title will always be in single line
2. Subtitle can be wrapped in multiple lines

**Regular:**
Padding: 
Min height
Title font size:
Subtitle font size:

**Large:**
Padding:
Min height
Title font size:
Subtitle font size:

**Condensed:**
Padding:
Min height
Title font size:
Subtitle font size:

**Comment by cjwinsor** [comment]
@Sanket8793 We are waiting on verification on the padding levels per size.  What you can do in the meantime is adjust the css so that its setting the padding for the item, and the height can just be the min-height now.  This way, once the final paddings are sorted out, you'll either have them already or have to make minor adjustments.

In addition, the main text had overflow hidden with ellipsis but after your changes its only hidden and doesn't show ellipsis.  The subtext should wrap.  And probably should thrown a `flex-shrink: 0` on the svg while we are at it as it does shrink when the text gets long.

**Comment by cjwinsor** [comment]
@Sanket8793 I've worked out what I believe is the solution for the design here, at this time, based on what I have available.
This code pen is me creating the desired design spacing considering mainly the figma guidelines for dropdowns but also some influence from other documentation for lists.
https://codepen.io/cjwinsor/pen/OJqJbmX?editors=1100

If you can achieve this same design then we can approve the PR.

Checklist (that i can think of now):
- [ ] Do long values have ellipsis?
- [ ] Does the subtext wrap when its long?
- [ ] Do you have any requirements on what to do if the subtext is long? If you are asked to make it ellipsis, consider a setting for wrapping subtext that is true by default.  
- [ ] Do the spacing and alignments match the codepen with and without subtext for all 3 sizes?
- [ ] Is the gap between the icon on the right and the text correct?

Ideally my codepen has enough css in it to account for the scenarios.

image

**Comment by Sanket8793** [comment]
@cjwinsor I have updated the style and updated the design according to the code pen, currently we make it ellipsis for main text and sub text when they are long.

**Comment by cjwinsor** [comment]
Comparing the latest from the branch, the styling doesn't seem to quiet match what was provided
image

Also, my expectation was that the sub-text would wrap and in order for it to be truncated it would need a property to control that.

**Comment by Sanket8793** [comment]
Do long values have ellipsis? -Yes
 
image

 Does the subtext wrap when its long? - Yes
 
 image
 
 Do you have any requirements on what to do if the subtext is long? If you are asked to make it ellipsis, consider a setting for wrapping subtext that is true by default. - I added setting for wrapping subtext that is true by default
 
 image

 Do the spacing and alignments match the codepen with and without subtext for all 3 sizes? - Yes
 
image

 Is the gap between the icon on the right and the text correct? - Yes

image

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
