### PR TITLE
Input: Add `autocapitalize`, `autocorrect`, `enterkeyhint`, and `spellcheck `properties

### PR DESCRIPTION
**Pull request by austinoneil**
## Description

Add autocapitalize, autocorrect, enterkeyhint, and spellcheck properties to input

References #2347

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Added unit tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
Nice! looks good.. but we need to have the additional controls to the demo canvas:
https://deploy-preview-2351--moduswebcomponents.netlify.app/?path=/story/user-inputs-text-input--default
(`autocapitalize`, `autocorrect`, `enterkeyhint`, and `spellcheck` options should be available here)

I don't think we need demos of them on the Docs page, can you please remove?

**Comment by austinoneil** [comment]
@coliff done.

**Comment by coliff** [comment]
- autocapitalize is appearing twice
- spellcheck is missing
- changing the values of the autocapitalize, autocorrect and enterkeyhint does not change the input at all. See screenshot:
image
We expect the input with id="mwc_id_0_text_input" here to have enterkeyhint="done" autocapitalize="sentences" autocorrect="off"

**Comment by austinoneil** [comment]
Oops.  Fixed.

**Comment by coliff** [comment]
thanks for work on this so far - still a few more things:
- `autocapitalize` by default should not be set at all. autocapitalize attribute should not be set on the `mwc_id_9_text_input` in the canvas example. (autocapitalize is the default on mobile devices usually anyway). So the dropdown in the Controls as standard should be 'Choose option...'
- `autocorrect` by default should not be set at all. autocorrect attribute should not be set on the `mwc_id_9_text_input` in the canvas example. (autocorrect is the default on mobile devices usually anyway). So the dropdown in the Controls as standard should be 'Choose option...'
- `enterkeyhint` should not have an option pre-selected - so have a ('Choose option...') selected.
- `spellcheck` should be a dropdown with true or false options - but by default nothing selected ('Choose option...').

**Comment by austinoneil** [comment]
I made the changes (except for spellcheck, as that is an attribute that is `true` if it's included, much like `disabled`).

**Review by coliff — APPROVED** [review]

**Review by coliff — APPROVED** [review]

**Comment by kuhnboy** [comment]
@austinoneil Why make autocorrect: boolean | 'off' | 'on'; 

Why not stick to just an enumeration or just a boolean?

**Comment by austinoneil** [comment]
@kuhnboy  When I as a developer see `autocorrect` as an attribute, my instinct tells me that it is a `boolean` input; however, the [`autocorrect`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#autocorrect) attribute on `input` takes `"on"` and `"off"` as values.  I included both because doing so makes the library easier to use without creating any obvious problems.

**Comment by austinoneil** [comment]
@kuhnboy That said, it does look like this was causing issues with `autocapitalize` in react (see #2412), so if needed, we can just use `"on"` and `"off"` (or just `boolean`)

**Pull request merged**
