### PR TITLE
Add File Dropzone component

### LINKED ISSUE #421: File Upload Dropzone Component
As an engineer, I want to have the file upload dropzone component available in web components, so I can use it in my application.

REF: [modus.trimble.com/components/file-upload-dropzone](https://modus.trimble.com/components/file-upload-dropzone/)

### PR DESCRIPTION
**Pull request by ryan-henness-trimble**
## Description

Add the File Dropzone component. Since this component was hard to write tests for (creating Files is not easy), and it feels subject to change, minimal tests were written.

Closes #421 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update

## How Has This Been Tested?

Minimal unit and e2e tests. Manual testing through the Storybook site.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
sorry not reviewed yet... we need to get Netlify deploy previews working again to make this easier!

**Comment by ryan-henness-trimble** [comment]
No worries! We should look into pulling down PRs locally as well, that could be helpful

**Comment by coliff** [comment]
I haven't been able to build and test this - getting an error:

```
PS C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook> npm run storybook

> mwc-storybook@0.0.0 storybook
> start-storybook -p 6006

info @storybook/web-components v6.4.19
info
info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
info => Serving static files from ./.\public at /
info => Loading custom manager config
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using default Webpack4 setup
(node:50740) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
14% building 34/42 modules 8 active C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\@storybook\addon-a11y\dist\esm\highlight.js
info => Using cached manager
webpack built preview e087dfcede64f25320e9 in 13869ms
× ｢wdm｣: Hash: e087dfcede64f25320e9
Version: webpack 4.46.0
Time: 13869ms
Built at: 17/05/2022 19:17:07
                            Asset      Size        Chunks                          Chunk Names
               0.iframe.bundle.js   903 KiB             0  [emitted]        [big]  
           0.iframe.bundle.js.map  1.04 MiB             0  [emitted] [dev]
               1.iframe.bundle.js   228 KiB             1  [emitted]
           1.iframe.bundle.js.map   218 KiB             1  [emitted] [dev]
               2.iframe.bundle.js   206 KiB             2  [emitted]
           2.iframe.bundle.js.map   145 KiB             2  [emitted] [dev]
               3.iframe.bundle.js  9.15 KiB             3  [emitted]
           3.iframe.bundle.js.map  6.47 KiB             3  [emitted] [dev]
               4.iframe.bundle.js   103 KiB             4  [emitted]
           4.iframe.bundle.js.map  87.3 KiB             4  [emitted] [dev]
               5.iframe.bundle.js   372 KiB             5  [emitted]        [big]  
           5.iframe.bundle.js.map   412 KiB             5  [emitted] [dev]
               6.iframe.bundle.js  15.7 KiB             6  [emitted]
           6.iframe.bundle.js.map  16.6 KiB             6  [emitted] [dev]
               7.iframe.bundle.js   917 KiB             7  [emitted]        [big]  
           7.iframe.bundle.js.map  1.04 MiB             7  [emitted] [dev]
                      iframe.html  11.6 KiB                [emitted]
            main.iframe.bundle.js   759 KiB          main  [emitted]        [big]  main       
        main.iframe.bundle.js.map   391 KiB          main  [emitted] [dev]         main       
    runtime~main.iframe.bundle.js  36.3 KiB  runtime~main  [emitted]               runtime~main
runtime~main.iframe.bundle.js.map  37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
    vendors~main.iframe.bundle.js  3.86 MiB  vendors~main  [emitted]        [big]  vendors~main
vendors~main.iframe.bundle.js.map  3.12 MiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js ./node_modules/@storybook/web-components/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js 232 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 4.62 KiB {main} [built]
[./generated-stories-entry.js] 425 bytes {main} [built]
[./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js] 3.15 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
    + 1250 hidden modules

ERROR in ./.storybook/preview.js
Module not found: Error: Can't resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
 @ ./.storybook/preview.js 1:0-52 3:0-20
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js ./node_modules/@storybook/web-components/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.33 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 2.08 KiB {HtmlWebpackPlugin_0} [built]
ModuleNotFoundError: Module not found: Error: Can't resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\neo-async\async.js:2830:7
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\neo-async\async.js:6877:13
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
  using description file: C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\package.json (relative path: ./.storybook)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\package.json (relative path: ./loader)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.cjs doesn't exist
      as directory
        C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by ryan-henness-trimble** [comment]
> I haven't been able to build and test this - getting an error:
> 
> ```
> PS C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook> npm run storybook
> 
> > mwc-storybook@0.0.0 storybook
> > start-storybook -p 6006
> 
> info @storybook/web-components v6.4.19
> info
> info => Loading presets
> info Found existing addon "@storybook/addon-docs", skipping.
> info => Serving static files from ./.\public at /
> info => Loading custom manager config
> info => Using implicit CSS loaders
> info => Loading custom manager config
> info => Using default Webpack4 setup
> (node:50740) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
> you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
> 
> See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 14% building 34/42 modules 8 active C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\@storybook\addon-a11y\dist\esm\highlight.js
> info => Using cached manager
> webpack built preview e087dfcede64f25320e9 in 13869ms
> × ｢wdm｣: Hash: e087dfcede64f25320e9
> Version: webpack 4.46.0
> Time: 13869ms
> Built at: 17/05/2022 19:17:07
>                             Asset      Size        Chunks                          Chunk Names
>                0.iframe.bundle.js   903 KiB             0  [emitted]        [big]  
>            0.iframe.bundle.js.map  1.04 MiB             0  [emitted] [dev]
>                1.iframe.bundle.js   228 KiB             1  [emitted]
>            1.iframe.bundle.js.map   218 KiB             1  [emitted] [dev]
>                2.iframe.bundle.js   206 KiB             2  [emitted]
>            2.iframe.bundle.js.map   145 KiB             2  [emitted] [dev]
>                3.iframe.bundle.js  9.15 KiB             3  [emitted]
>            3.iframe.bundle.js.map  6.47 KiB             3  [emitted] [dev]
>                4.iframe.bundle.js   103 KiB             4  [emitted]
>            4.iframe.bundle.js.map  87.3 KiB             4  [emitted] [dev]
>                5.iframe.bundle.js   372 KiB             5  [emitted]        [big]  
>            5.iframe.bundle.js.map   412 KiB             5  [emitted] [dev]
>                6.iframe.bundle.js  15.7 KiB             6  [emitted]
>            6.iframe.bundle.js.map  16.6 KiB             6  [emitted] [dev]
>                7.iframe.bundle.js   917 KiB             7  [emitted]        [big]  
>            7.iframe.bundle.js.map  1.04 MiB             7  [emitted] [dev]
>                       iframe.html  11.6 KiB                [emitted]
>             main.iframe.bundle.js   759 KiB          main  [emitted]        [big]  main       
>         main.iframe.bundle.js.map   391 KiB          main  [emitted] [dev]         main       
>     runtime~main.iframe.bundle.js  36.3 KiB  runtime~main  [emitted]               runtime~main
> runtime~main.iframe.bundle.js.map  37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
>     vendors~main.iframe.bundle.js  3.86 MiB  vendors~main  [emitted]        [big]  vendors~main
> vendors~main.iframe.bundle.js.map  3.12 MiB  vendors~main  [emitted] [dev]         vendors~main
> Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
> [0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js ./node_modules/@storybook/web-components/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js 232 bytes {main} [built]
> [./.storybook/preview.js-generated-config-entry.js] 4.62 KiB {main} [built]
> [./generated-stories-entry.js] 425 bytes {main} [built]
> [./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js] 3.15 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.13 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.14 KiB {vendors~main} [built]
> [./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
>     + 1250 hidden modules
> 
> ERROR in ./.storybook/preview.js
> Module not found: Error: Can't resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
>  @ ./.storybook/preview.js 1:0-52 3:0-20
>  @ ./.storybook/preview.js-generated-config-entry.js
>  @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/web-components/config.js-generated-config-entry.js ./node_modules/@storybook/web-components/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
> Child HtmlWebpackCompiler:
>                           Asset      Size               Chunks  Chunk Names
>     __child-HtmlWebpackPlugin_0  6.33 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
>     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
>     [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 2.08 KiB {HtmlWebpackPlugin_0} [built]
> ModuleNotFoundError: Module not found: Error: Can't resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\Compilation.js:925:10
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:401:22
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:130:21
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:224:22
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\neo-async\async.js:2830:7
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\neo-async\async.js:6877:13
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\webpack\lib\NormalModuleFactory.js:214:25
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:213:14
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
>     at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
>     at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\Resolver.js:285:5
>     at eval (eval at create (C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
>     at C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
> resolve '../../loader' in 'C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\.storybook'
>   using description file: C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\storybook\package.json (relative path: ./.storybook)
>     Field 'browser' doesn't contain a valid alias configuration
>     using description file: C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\package.json (relative path: ./loader)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader doesn't exist
>       .mjs
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.mjs doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.js doesn't exist
>       .jsx
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.jsx doesn't exist
>       .ts
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.ts doesn't exist
>       .tsx
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.tsx doesn't exist
>       .json
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.json doesn't exist
>       .cjs
>         Field 'browser' doesn't contain a valid alias configuration
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader.cjs doesn't exist
>       as directory
>         C:\Users\coliff\Documents\GitHub\modus-web-components\stencil-workspace\loader doesn't exist
> 
> WARN Broken build, fix the error above.
> WARN You may need to refresh the browser.
> ```

oh hmm, did you run `npm run build` from the stencil-workspace? My guess is maybe the components weren't built so Stencil couldn't find them

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
got it building finally. I got it working by updating storybook to latest version...

Anyway great work on this PR. looks good :-)

**Pull request merged**
