### PR TITLE
Navbar: Remove Pressed State for the icon button after popup is closed

### PR DESCRIPTION
**Pull request by Sanket8793**
## Description

Remove Pressed State for the icon button after popup is closed

References #2272 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

when the popup is closed make sure that icon button is expected to return to the default state.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by zabdur-rahman** [comment]
@cjwinsor Can this ticket be looked at? It's been sitting for a couple of weeks.

**Comment by cjwinsor** [comment]
@zabdur-rahman @Sanket8793  Sorry about the delay, focus has been on other initiatives and tickets.  This particular PR demands a bit more of my time as I do not agree with the implementation and will need to come up with what I think is appropriate.  I was going to review later today now the previous blockers are resolved, but I'll review now.

A prop is added for `isDynamicButtonSlotOpen` which represents that someone could try to set this to `true` but that would have no affect as its not used in that capacity in the code.  I could not find any value in making it a public facing prop.    

In the `showButtonMenuById(id)` function, its setting this to true if `this.openButtonMenuId === id`.   Then it calls the function to `hideMenus()` which will set `this.openButtonMenuId = undefinded`.  The code continues to check if `this.openButtonMenuId !== id && !this.isDynamicButtonSlotOpen` before setting the `this.openButtonMenuId = id`.  Since `this.openButtonMenuId` was set to `undefined` in the previous step, the first condition will pass as long as the passed in `id` is not undefined.  The second condition will pass when whatever the previous state of `this.openButtonMenuId !== id`.  

If `this.isDynamicButtonSlotOpen` was a `const` inside of `showButtonMenuById` i don't think it changes how the code operates.  Also you're setting a prop without having it configured as `mutable: true` which means it will throw a warning when its updated inside the code as done here.  

Currently I don't know how to reproduce even when I try in the e-Builder QA3 environment it already removes the active state when I click elsewhere on the page, though the userway component never opens when I do click on the menu item. The "How Has This Been Tested?" area is the best spot to give details which enable me to quickly validate the scenario.  Screenshots, gifs, videos, code snippets all help to reduce the effort to review.  Both the issue writeup and the PR writeup are vague, leading me to save it for when I have time to review it thoroughly. In the future, I will try to indicate why PRs are not being prioritized so you have the opportunity to make adjustments as needed.

Can you add to this and future PRs:
- Reproduction case I can follow.
- Explanation of what the issue was
- Explanation on how this code change fixes the issue

**Comment by cjwinsor** [comment]
@Sanket8793 Thank you for the explanation and the video, I'm able to see the issue now.  The main code change I was looking for was to remove the `isDynamicButtonSlotOpen` prop `altogether` and simply use a `const` variable inside `showButtonMenuById`.

**Comment by Sanket8793** [comment]
> @Sanket8793 Thank you for the explanation and the video, I'm able to see the issue now. The main code change I was looking for was to remove the `isDynamicButtonSlotOpen` prop `altogether` and simply use a `const` variable inside `showButtonMenuById`.

@cjwinsor I updated the code using `const` variable inside `showButtonMenuById`.

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
