### PR TITLE
Date Picker: Modify date out of bounds UI

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Updated the body of calendar by adding text "The selected date is not available" the current date is out of range from the minimum and maximum date calculated in goToNearestBoundaryDate() and a text "Go to available dates" which will redirect to the nearby date calculated goToNearestBoundaryDate()

References #
#1772

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rthanga1 — CHANGES_REQUESTED** [review]
Code looks good. But there are some functionality issues I see
1. Need to add some padding above the 'The selected date is not available' link. This happens when the picker has more than 5 rows
2. When 'Go to available dates' is clicked, it should not change the date in the input field. Rather it should just navigate to the available dates

Screen Shot 2024-01-23 at 3 15 05 PM

**Comment by ElishaSamPeterPrabhu** [comment]
> Code looks good. But there are some functionality issues I see
> 
> 1. Need to add some padding above the 'The selected date is not available' link. This happens when the picker has more than 5 rows
> 2. When 'Go to available dates' is clicked, it should not change the date in the input field. Rather it should just navigate to the available dates
> 
> Screen Shot 2024-01-23 at 3 15 05 PM

Addressed after the latest commit : [aed4ab8](https://github.com/trimble-oss/modus-web-components/pull/2048/commits/aed4ab8db41c6365a868017adf59e9d66f33a64c)

**Review by rthanga1 — APPROVED** [review]

**Comment by yshnaviganapathi** [comment]
@ElishaSamPeterPrabhu , I have raised an issue with the date picker component.  This issue was not introduced by the recent pull request; it already existed in the previous codebase. Please refer to the bug ID: https://github.com/trimble-oss/modus-web-components/issues/2095.

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu , I have raised an issue with the date picker component. This issue was not introduced by the recent pull request; it already existed in the previous codebase. Please refer to the bug ID: #2095.

The maximum and minimum dates are handled by states which are updated when loading the component for the first time , since  its also the expected behavior, this issue can be closed

**Comment by cjwinsor** [comment]
@ElishaSamPeterPrabhu Only thing this is missing is some tests

**Comment by ElishaSamPeterPrabhu** [comment]
> @ElishaSamPeterPrabhu Only thing this is missing is some tests

Added tests

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
