### PR TITLE
Navbar: Add Active/Pressed State to buttons

### PR DESCRIPTION
**Pull request by Sanket8793**
Add Active/Pressed State to Navbar Buttons

References #2035 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?
  
Make sure that when button is pressed, it should display an active state

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cjwinsor** [comment]
@Sanket8793 The help doesn't have a menu, so with this change it should just show it as active until someone clicks somewhere else.  Is there a use case for this.  The issue seems to be for the navbar buttons, but it was too generic and lacks screenshots or details.  Does this have to do with e-Builders resource center and needing it to mark the help icon as active while that is open?  If so, we might need a solution that doesn't set the icon as pressed under every state.

**Comment by DafneeZambrano** [comment]
Hi Chris, for buttons that don't open a menu (like search) we use a quick press. So the state is active while the user is pressing the button. This is an accessibility requirement to indicate the action to the user. 

If the button triggers a menu, then it stays in an active state until the user closes the menu.

For the help menu, we will eventually trigger the Gainsight menu, so we will need it as an active state then.

**Review by rthanga1 — CHANGES_REQUESTED** [review]
Holding for Chris's comment get addressed

**Comment by cjwinsor** [comment]
> Hi Chris, for buttons that don't open a menu (like search) we use a quick press. So the state is active while the user is pressing the button. This is an accessibility requirement to indicate the action to the user.
> 
> If the button triggers a menu, then it stays in an active state until the user closes the menu.
> 
> For the help menu, we will eventually trigger the Gainsight menu, so we will need it as an active state then.

@DafneeZambrano The current implementation keeps the button active even after the click action is completed.  So it remains marked as active until another element is interacted with.  So if a popup were to be triggered then it remains active until the user comes back to the page and interacts with anything else, which is a strange behavior.  

I agree that while its being clicked it should be active, and if it is showing something then ideally its still marked active as well, though I need a moment to consider how best to work with your desire to have a gainsight menu show at that location and keep the icon active at the same time. I will come back to this PR later in the day.

**Comment by cjwinsor** [comment]
There is a meeting to discuss the particulars on 1/24 at 11am EST.

**Comment by cjwinsor** [comment]
This ticket was discussed in a meeting with the two teams. I'm waiting to hear if they need technical help to resolve their need here after they check their options with gainsight.

**Comment by cjwinsor** [comment]
@Sanket8793 I see you are adding a bunch of icon files, perhaps you had a bad merge of main?  Can you fix your branch?  Also I don't seem to see any different handling for the help icon not being marked active after click, was there any intended change there?

**Comment by zabdur-rahman** [comment]
> @Sanket8793 I see you are adding a bunch of icon files, perhaps you had a bad merge of main? Can you fix your branch? Also I don't seem to see any different handling for the help icon not being marked active after click, was there any intended change there?

@cjwinsor We won't be adding special handling for the help icon. An issue will be made with Gainsight to address it.

**Comment by cjwinsor** [comment]
@zabdur-rahman @Sanket8793 PR still has issue with having all those extra files added for icons. Please sort out your branch so it only has your changes and doesn't have the special handing for help, then we can move forward.

**Comment by cjwinsor** [comment]
@Sanket8793 The latest Modus Web Components switched out the `IconMap` for the `ModusIconMap`, which gives all the Modus Icons a pressed state.  The Navbar now uses `ModusIconMap`.  Is this PR necessary?  I'm actually looking to see if we can move away from using the icons in `svgs` in favor for the full icon list available from `ModusIconMap`  and the `generated-icons`.

**Comment by Sanket8793** [comment]
@cjwinsor Since the Navbar uses modus icons from ModusIconMap we don't need these changes, I'm going to close this PR

**Review by cjwinsor — APPROVED** [review]

**Pull request merged**
