### PR TITLE
Autocomplete: Update behaviour

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Monitoring text entered and showing all options during focus while showing filtered options only when text entered with `@State() textEntered`.
- Shows all options duing focus updated `displayOptions()`.

References #2282 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by coliff** [comment]
Test failing:
image

**Comment by ElishaSamPeterPrabhu** [comment]
> Test failing: image

Working on it moving into draft

**Comment by ElishaSamPeterPrabhu** [comment]
> Test failing: image

now passing

**Comment by cjwinsor** [comment]
Developers at e-Builder are working on this issue and have a strong understanding for the desired outcome.  In the future we should look to identify issues that are being worked on by external contributors better.

**Pull request closed without merging**
